[Server]
Port=":12307"
key="spppk"
[DB]
Addr = "localhost"
User = "bigdirector_temp"
Pass = "akdbJnaKApJfxsrd"
DBName = "bigdirector_temp"
[DBDev]
Addr = "localhost"
User = "root"
Pass = "123456"
DBName = "bigdirector"
[Redis]
Addr = "localhost:6379"
Pass = ""
DB = 0