[Server]
Port = ":12309"
Sign = "spppk"
[DB]
Addr = "localhost"
Port = "3306"
User = "director"
Pass = "akdbJnaKApJfxsrd"
DBName = "bigdirector"
[DBDev]
Addr = "localhost"
Port = "3306"
User = "root"
Pass = "root"
DBName = "bigdirector"
[Redis]
Addr = "localhost:6379"
Pass = ""
DB = 0
[Casbin]
Model = "config/model.conf"