basePath: /BigDirector
host: api.zerokirin.online
info:
  contact:
    email: lightning@zerokirin.online
    name: 00LT00
    url: http://blog.zerokirin.online
  description: 我是大导演API
  title: BigDirector API
  version: "2.0"
paths: {}
swagger: "2.0"
