name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: aliyun
    env:
      WX_APPID: ${{ secrets.WX_APPID }}
      WX_APPSECRET: ${{ secrets.WX_APPSECRET }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Get dependencies
      working-directory: .
      run:  go mod tidy

    - name: Build
      run:  |
        go build -o main ./cmd/main.go
        
    - name: Move file
      run: |
        mkdir ${{ github.workspace }}/dist
        mv main ${{ github.workspace }}/dist
        ls
        cd ${{ github.workspace }}/dist
        pwd
        ls
        
    - name: Upload ./main to Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
    # Artifact name
          name: exec
    # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/dist/main
    # The desired behavior if no files are found using the provided path.
      
  push-to-aliyun:
    runs-on: ubuntu-latest
    needs: [build]
    environment: ssh-deploy
    steps:
    - name: mkdir
      run: |
        mkdir ${{ github.workspace }}/dist/
    
    - name: Download to ${{ github.workspace }}/dist/
      uses: actions/download-artifact@v2.0.8
      with:
    # Artifact name
        name: exec
    # Destination path
        path: ${{ github.workspace }}/dist/
       
    - name: pwd
      run: |
        pwd
        cd dist
        pwd
        ls
        
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
    # Private Key
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    # Remote host
        REMOTE_HOST: ${{secrets.SSH_HOST}}
    # Remote user
        REMOTE_USER: root
        SOURCE: dist/
        TARGET: /root/github-actions
    
    
    

